##########################################################################
##  v      #                  The Coq Proof Assistant                   ##
## <O___,, # CNRS-Ecole Polytechnique-INRIA Futurs-Universite Paris Sud ##
##   \VV/  #                                                            ##
##    //   #   Makefile automagically generated by coq_makefile V8.2    ##
##########################################################################

# WARNING
#
# This Makefile has been automagically generated
# Edit at your own risks !
#
# END OF WARNING

#
# This Makefile was generated by the command line :
# coq_makefile -f Make -o Makefile 
#

#########################
#                       #
# Libraries definition. #
#                       #
#########################

OCAMLLIBS:=
COQLIBS:= -R . Hardware
COQDOCLIBS:=-R . Hardware

##########################
#                        #
# Variables definitions. #
#                        #
##########################

CAMLP4LIB:=$(shell $(CAMLBIN)camlp5 -where 2> /dev/null || $(CAMLBIN)camlp4 -where)
CAMLP4:=$(notdir $(CAMLP4LIB))
COQSRC:=-I $(COQTOP)/kernel -I $(COQTOP)/lib \
  -I $(COQTOP)/library -I $(COQTOP)/parsing \
  -I $(COQTOP)/pretyping -I $(COQTOP)/interp \
  -I $(COQTOP)/proofs -I $(COQTOP)/syntax -I $(COQTOP)/tactics \
  -I $(COQTOP)/toplevel -I $(COQTOP)/contrib/correctness \
  -I $(COQTOP)/contrib/extraction -I $(COQTOP)/contrib/field \
  -I $(COQTOP)/contrib/fourier -I $(COQTOP)/contrib/graphs \
  -I $(COQTOP)/contrib/interface -I $(COQTOP)/contrib/jprover \
  -I $(COQTOP)/contrib/omega -I $(COQTOP)/contrib/romega \
  -I $(COQTOP)/contrib/ring -I $(COQTOP)/contrib/xml \
  -I $(CAMLP4LIB)
ZFLAGS:=$(OCAMLLIBS) $(COQSRC)
OPT:=
COQFLAGS:=-q $(OPT) $(COQLIBS) $(OTHERFLAGS) $(COQ_XML)
COQC:=$(COQBIN)coqc
COQDEP:=$(COQBIN)coqdep -c
GALLINA:=$(COQBIN)gallina
COQDOC:=$(COQBIN)coqdoc
CAMLC:=$(CAMLBIN)ocamlc -rectypes -c
CAMLOPTC:=$(CAMLBIN)ocamlopt -c
CAMLLINK:=$(CAMLBIN)ocamlc
CAMLOPTLINK:=$(CAMLBIN)ocamlopt
GRAMMARS:=grammar.cma
CAMLP4EXTEND:=pa_extend.cmo pa_macro.cmo q_MLast.cmo
PP:=-pp "$(CAMLBIN)$(CAMLP4)o -I . -I $(COQTOP)/parsing $(CAMLP4EXTEND) $(GRAMMARS) -impl"

###################################
#                                 #
# Definition of the "all" target. #
#                                 #
###################################

VFILES:=./Libraries/Lib_Boolean/Lib_Bool.v\
  ./Libraries/Lib_Boolean/Lib_Zerob.v\
  ./Libraries/Lib_Prop.v\
  ./Libraries/Lib_Set_Products.v\
  ./Libraries/Lib_Lists/Dependent_lists.v\
  ./Libraries/Lib_Lists/Lists_of_lists.v\
  ./Libraries/Lib_Arithmetic/Lib_Div_Even_Odd.v\
  ./Libraries/Lib_Arithmetic/Lib_Pred.v\
  ./Libraries/Lib_Arithmetic/Lib_Plus.v\
  ./Libraries/Lib_Arithmetic/Lib_Square.v\
  ./Libraries/Lib_Arithmetic/Lib_Arith.v\
  ./Libraries/Lib_Arithmetic/Lib_Fact.v\
  ./Libraries/Lib_Arithmetic/Lib_Eq_Le_Lt.v\
  ./Libraries/Lib_Arithmetic/Lib_Exp.v\
  ./Libraries/Lib_Arithmetic/Lib_Mult.v\
  ./Libraries/Lib_Arithmetic/Lib_Dec.v\
  ./Libraries/Lib_Arithmetic/Lib_Minus.v\
  ./Factorization/Factorization_Prog.v\
  ./Factorization/Lib_Numerals/Compare_Num.v\
  ./Factorization/Lib_Numerals/Compare_Nat.v\
  ./Factorization/Lib_Numerals/Numerals.v\
  ./Factorization/Lib_Numerals/Lists_of_Numerals.v\
  ./Factorization/Factorization_Synth.v\
  ./Factorization/Factorization_Verif.v\
  ./Factorization/Factorization.v\
  ./Factorization/Linear_Structures.v\
  ./Factorization/Comparator/Comparator_Relation.v\
  ./Factorization/Comparator/extract.v\
  ./Factorization/Comparator/Comp_Simpl.v\
  ./Factorization/Comparator/Comp_Synth.v\
  ./Factorization/Comparator/Comp_Verif.v\
  ./Factorization/Comparator/Comp_Prog.v
VOFILES:=$(VFILES:.v=.vo)
GLOBFILES:=$(VFILES:.v=.glob)
VIFILES:=$(VFILES:.v=.vi)
GFILES:=$(VFILES:.v=.g)
HTMLFILES:=$(VFILES:.v=.html)
GHTMLFILES:=$(VFILES:.v=.g.html)

all: $(VOFILES) Factorization/Comparator/comp.ml\
  Factorization/Comparator/comp\
  Factorization/Comparator/comp.cmi\
  test
spec: $(VIFILES)

gallina: $(GFILES)

html: $(GLOBFILES) $(VFILES)
	- mkdir html
	$(COQDOC) -toc -html $(COQDOCLIBS) -d html $(VFILES)

gallinahtml: $(GLOBFILES) $(VFILES)
	- mkdir html
	$(COQDOC) -toc -html -g $(COQDOCLIBS) -d html $(VFILES)

all.ps: $(VFILES)
	$(COQDOC) -toc -ps $(COQDOCLIBS) -o $@ `$(COQDEP) -sort -suffix .v $(VFILES)`

all-gal.ps: $(VFILES)
	$(COQDOC) -toc -ps -g $(COQDOCLIBS) -o $@ `$(COQDEP) -sort -suffix .v $(VFILES)`



###################
#                 #
# Custom targets. #
#                 #
###################

Factorization/Comparator/comp.ml: Factorization/Comparator/Comp_Synth.vo
	$(COQBIN)coqtop $(COQFLAGS) -silent -batch -load-vernac-source Factorization/Comparator/extract.v

Factorization/Comparator/comp: Factorization/Comparator/comp.ml Factorization/Comparator/comp.cmi
	ocamlopt -I Factorization/Comparator -o Factorization/Comparator/comp Factorization/Comparator/comp.ml Factorization/Comparator/comp.mli Factorization/Comparator/main.ml

Factorization/Comparator/comp.cmi: Factorization/Comparator/comp.mli
	ocamlc Factorization/Comparator/comp.mli

test: Factorization/Comparator/comp
	@echo '******* test: comparing two numbers *******'
	./Factorization/Comparator/comp 12365876 646848674
	@echo '************** End of test ****************'

####################
#                  #
# Special targets. #
#                  #
####################

.PHONY: all opt byte archclean clean install depend html

%.vo %.glob: %.v
	$(COQC) -dump-glob $*.glob $(COQDEBUG) $(COQFLAGS) $*

%.vi: %.v
	$(COQC) -i $(COQDEBUG) $(COQFLAGS) $*

%.g: %.v
	$(GALLINA) $<

%.tex: %.v
	$(COQDOC) -latex $< -o $@

%.html: %.v %.glob
	$(COQDOC) -glob-from $*.glob  -html $< -o $@

%.g.tex: %.v
	$(COQDOC) -latex -g $< -o $@

%.g.html: %.v %.glob
	$(COQDOC) -glob-from $*.glob -html -g $< -o $@

%.v.d: %.v
	$(COQDEP) -glob -slash $(COQLIBS) "$<" > "$@" || ( RV=$$?; rm -f "$@"; exit $${RV} )

byte:
	$(MAKE) all "OPT:=-byte"

opt:
	$(MAKE) all "OPT:=-opt"

install:
	mkdir -p `$(COQC) -where`/user-contrib
	cp -f $(VOFILES) `$(COQC) -where`/user-contrib

Makefile: Make
	mv -f Makefile Makefile.bak
	$(COQBIN)coq_makefile -f Make -o Makefile


clean:
	rm -f *.cmo *.cmi *.cmx *.o $(VOFILES) $(VIFILES) $(GFILES) *~
	rm -f all.ps all-gal.ps all.glob $(VFILES:.v=.glob) $(HTMLFILES) $(GHTMLFILES) $(VFILES:.v=.tex) $(VFILES:.v=.g.tex) $(VFILES:.v=.v.d)
	- rm -rf html
	- rm -f Factorization/Comparator/comp.ml
	- rm -f Factorization/Comparator/comp
	- rm -f Factorization/Comparator/comp.cmi
	- rm -f test

archclean:
	rm -f *.cmx *.o


-include $(VFILES:.v=.v.d)
.SECONDARY: $(VFILES:.v=.v.d)

# WARNING
#
# This Makefile has been automagically generated
# Edit at your own risks !
#
# END OF WARNING

